version: "3.9"

services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 4s
      timeout: 4s
      retries: 4
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - PORT
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env:ro

volumes:
  db_data:
